### ISSUE TITLE
M8C4 timed out frequently

### ISSUE THREAD

**Issue by noralinn** [blumzi/LAST_issues#10]
M8C4 timed out while taking observations, didn't save images, or didn't communicate at all. But Unit.checkWholeUnit succeeded without fixing anything.

Shutting down and restarting the mount fixed it.

Reporting here in case the problem reappears.

**Comment by EastEriq** [comment]
For what I remember, timing out when an exposure should be ready is mostly associated with poor usb cables or EMI. 

Just a note on CheckWholeUnit: CheckWholeUnit(0,1) only does the basic check of seeing if the slave is online and some camera properties make sense, and power cycles the camera if not. A more stringent stress test would be CheckWholeUnit(1,1), which takes several images, but it is time consuming.
