### ISSUE TITLE
install INPOP and OrbitalEl on all last computers

### ISSUE THREAD

**Issue by EranOfek** [blumzi/LAST_issues#14]
In last-tool matlab section:
add the following commands (id doesn't exist):

```
I = Installer;
I.install('INPOP');
I.install('MinorPlanets');
I.install('MinorPlanetsCT');
```

Execute on all computers.

**Comment by EastEriq** [comment]
Pleas keep me posted on progress. LAST code is going to add a dependence on INPOP (currently for development in this branch: https://github.com/PolishookDavid/LAST_OCS/tree/j2000inHeader)

**Comment by EranOfek** [comment]
Done

**Comment by EranOfek** [comment]
(on almost all computers)
