### ISSUE TITLE
Weather station stopped working

### ISSUE THREAD

**Issue by noralinn** [blumzi/LAST_issues#17]
![Screenshot from 2024-01-25 07-16-17](https://github.com/blumzi/LAST_issues/assets/14293969/4bf3101c-0af3-4798-a194-e63f353e66c9)

**Comment by EastEriq** [comment]
Hm, seems strange that the Davis was working briefly, then was off a day, then again on briefly. I'll restart the `last-meteologger` service to see if it is only a software problem.

**Comment by EastEriq** [comment]
Just restarting didn't help. I'll try an interactive session to see what is going on. However, even more strangely, it seems that there is no connection with the enclosure controller since 18/1

**Comment by EastEriq** [comment]
The Davis resurrected after a few service stops and starts and usbresets, whichever helped.

The usb port of the outdoor arduino is not known to the system, I suspect the cable is disconnected.

The enclosure controller is not reachable through ethernet. I also suspect that its ethernet cable is disconnected, because electrically it must have been powered, since Nora reported that the roof has opened last night.

If cables are not the problem, I can only suggest to try to reboot last0 and to turn off and on the enclosure cabinet.

**Comment by noralinn** [comment]
Right after closing the roof last night something was beeping for 10s and then stopped.
Tonight I couldn't open it until flipping up a switch inside the closet (the one next to the round dial).
So was that an overcurrent?

I'll look for the arduino cable tomorrow.

**Comment by EastEriq** [comment]
Quite likely, ups out of battery. But that doesn't explain why it has been out of the network for a week

Il 25 gen 2024 19:57, noralinn ***@***.***> ha scritto:

Right after closing the roof last night something was beeping for 10s and then stopped.
Tonight I couldn't open it until flipping up a switch inside the closet (the one next to the round dial).
So was that an overcurrent?

I'll look for the arduino cable tomorrow.

**Comment by noralinn** [comment]
The outdoor arduino is powered (lights on). I pulled and reconnected the cable at last0. Restarted last0 (for unrelated reasons). It's still not working. Does one have to restart anything?

**Comment by EastEriq** [comment]
No, after a reboot the meteologger service is automatically restarted. `systemctl status last-meteologger` as of now still reports no connection to the outdoor arduino. This is not the first time we have issues, clearly a better cabling solution is required.

**Comment by EastEriq** [comment]
Quite likely that's the same cause of issue #27! I think I remember that one of the arduini was registering as ACM.

**Comment by EastEriq** [comment]
Indeed and indeed. Solved by installing the relevant linux-modules-extra-5.15.0-92-generic and rebooting the machine
