### ISSUE TITLE
The header coordinates always include distortions, even if goToTarget2 with ApplyDist=false was used.

### ISSUE THREAD

**Issue by EranOfek** [blumzi/LAST_issues#19]
The header coordinates always include distortions, even if goToTarget2 with ApplyDist=false was used.
While goToTarget2 works properly, the constructHeader functions does not know if the use used ApplyDist=false.
Therefore, the distortion is always added to the header.

This needs to be changed - only reasonable option is to add a property to the Mount object...

Meanwhile,  when pointing model is performed, a temporary solution is:
(1) Set the offsets in the configuration pointing model to zeros.
(2) shutdown the unit and restart (the configuration is read on connection).
(3) still best to use goToTarget2(RA, Dec, [0 0], false) as in the future steps (1) and (2) will not be needed.

**Comment by EranOfek** [comment]
Fixed with new schema

**Comment by EastEriq** [comment]
But: https://github.com/PolishookDavid/LAST_OCS/issues/29. To be fixed for https://github.com/PolishookDavid/LAST_OCS/milestone/1

**Comment by EranOfek** [comment]
I don't think these are related.

**Comment by EastEriq** [comment]
Right, they aren't really, for me you can close it again
