### ISSUE TITLE
M8F4 focuser moves, but the mirror doesn't (image stays the same)

### ISSUE THREAD

**Issue by noralinn** [blumzi/LAST_issues#22]
One hears the focuser moving, and the reported focuser position changes, but the image always looks the same even for large shifts. The three other telescopes focus well, so cables not switched.

Probably the focuser is too loose or the mirror is stuck.

**Comment by EastEriq** [comment]
>M8F4 - works now - the screw of the  focusers over the telescope was not closed enough
