### ISSUE TITLE
M4F3 doesn't communicate since a few weeks

### ISSUE THREAD

**Issue by noralinn** [blumzi/LAST_issues#23]
Persistent issue since a long time. Pulling and reconnecting cable didn't help. Neither did changing the cable. Replace focuser?

```
Unit.Focuser{3}.classCommand('Pos')

ans =

   NaN
```

**Comment by EastEriq** [comment]
It may even be that the focuser motor is fried, but for what I remember that would be our first time. It may also be that the usb card is faulty, I remember we had a similar problem long time ago on M1. I don't remember if the card resurrected after a few days (static electricity?), or if we permanently hooked focuser and camera to other usb ports.

I'd suggest the following test still:

- If the other focuser on the last04w works, connect F3 to that port.
- close the matlab session in which you defined the Unit, open a new one
- `seriallist`. It should report something like `/dev/ttyACM0`
- `F=inst.CelestronFocuser; F.connect('/dev/ttyACM0')`  (or whatever serial resource was listed) - what does it say?
- if `connect` succeeded, `F.Status`, `F.Pos`, `F.Limits` - do they work?

**Comment by simonegarrappa** [comment]
Solved by Enrico. 

Solution: PhysicalAddress of M3F3 was modified in the config file but didn't correspond to the port where the focuser is actually connected. The corrected config file is also committed on github.

**Comment by EastEriq** [comment]
Lesson learned, LABEL CABLES AND SOCKETS.
