### ISSUE TITLE
I keep finding machines needing confirmation of fingerprint

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_issues#26]
The last one I ran into was last03e, demanding authentication for `ssh`'ing to 10.23.1.5 (itself, but by IP).

Inability of `rsh`'ing without password prevents slaves from connecting, and thus is crucial. On the spot the problem is quickly fixed with `ssh-copy-id`, but why it presents itself again and again?

**Comment by EastEriq** [comment]
Today, last02w doesn't ssh to itself, but
```
ocs@last02e:~$ ssh-copy-id 10.23.1.3

/usr/bin/ssh-copy-id: ERROR: failed to open ID file '/home/ocs/.ssh/id_rsa_last': Permission denied
	(to install the contents of '/home/ocs/.ssh/id_rsa_last.pub' anyway, look at the -f option)
ocs@last02e:~$ ssh-copy-id 10.23.1.4

/usr/bin/ssh-copy-id: ERROR: failed to open ID file '/home/ocs/.ssh/id_rsa_last': Permission denied
	(to install the contents of '/home/ocs/.ssh/id_rsa_last.pub' anyway, look at the -f option)
ocs@last02e:~$ ssh-copy-id ocs@10.23.1.4
```

**Comment by EastEriq** [comment]
```
ocs@last02w:~$ ssh-copy-id 10.23.1.4
The authenticity of host '10.23.1.4 (10.23.1.4)' can't be established.
ECDSA key fingerprint is SHA256:SFf/SeNmjf5rExilF8BNM5jl6d9D8+QhiVK6AcRVeB8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed

/usr/bin/ssh-copy-id: WARNING: All keys were skipped because they already exist on the remote system.
		(if you think this is a mistake, you may want to use -f option)

```

**Comment by EastEriq** [comment]
Also reported here, I forgot
https://github.com/blumzi/LAST_tools/issues/31

**Comment by blumzi** [comment]
`last-tool -n check|make ssh` takes care of:
* having the id_rsa copied from the LAST-CONTAINER to the machine, so we have the same on ALL machines
* adding the id_rsa.pub to the authorized_keys
* uses ssh-keyscan to add whatever machine is on-line to known_hosts
It is detailed [here](https://github.com/blumzi/LAST_tools/wiki/sections#ssh)

Why do you copy the id manually?

**Comment by EastEriq** [comment]
> Why do you copy the id manually?

Just out of laziness because I don't remember the last-tool options. But the point is, why I find that the keys are missing here and there again?
