### ISSUE TITLE
Mount 6 entered in clicking resonance

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_issues#5]
on 14/12/2023, when commanded to move (ha,Dec)= (90,81)-->(270,81). Likely it went into overcurrent fault and then deactivated one of the two axes, but `.waitFinish` did not report it nor stopped (see https://github.com/EastEriq/LAST_XerxesMount/issues/7).

Probably Yahel, who was on site twisted the HA axis of 1 turn when trying to restore operations, causing cable entanglement, which was further revealed, but this is not confirmed.

**Comment by EranOfek** [comment]
Likely related to an existing open issue
