### ISSUE TITLE
last06e/data2 issues - run fsck or replace disk

### ISSUE THREAD

**Issue by EranOfek** [blumzi/LAST_issues#65]
last06e/data2 issues:

ocs@last06e:/last06e/data1/archive/LAST.01.06.01/failed$ cdcam2
ocs@last06e:/last06e/data2/archive/LAST.01.06.02$ ls
ls: reading directory '.': Input/output error

Suggest fsck, and if there are problems try to backup the disk and replace it.

**Comment by blumzi** [comment]
we're going to replace the whole last06e machine
