### ISSUE TITLE
new ethernet card types in the recently purchased LAST computers 

### ISSUE THREAD

**Issue by agioffe** [blumzi/LAST_issues#67]
Several (2 or 3?) most recent LAST computers have newer ethernet cards, and this leads to the interface being recognized as **enp79s0** instead of **enp67s0** hard-coded in _last-tools_. 
To cope with it, create a file **/etc/systemd/network/10-eth.rules** having such lines:

[Match]
MACAddress=xx:xx:xx.. (the actual MAC of the card, can be see, e.g., with _> ip a_)

[Link]
Name=enp67s0

Also, before installing LAST environment with last-tools -n make <something>
install colorized-logs, git, and autofs by hand as
> apt install git
> apt install autofs
> apt install colorized-logs

**Comment by EastEriq** [comment]
> Finally, it is desirable to install and configure _matlab redis cli_ as well.

Just a note: `matlab/LAST/MatlabRedis` is a package that is easily cloned from github, and as such is already included in
https://github.com/blumzi/LAST_tools/blob/d0f0057ba191fe3a38484910dfb8f6eea1d8dac9/files/github-repos.gledmagicwater#L44

`last-tool -n enforce last-software -s gledmagicwater` already installs it together with all the other useful packages pulled from github.

This sits on top of Redis, which has to be installed separately, like discussed in https://github.com/blumzi/LAST_tools/issues/42. Together with Redis, it is also convenient to install `redisinsight`.
