### ISSUE TITLE
4w asks if I'm ocs or enrico 

### ISSUE THREAD

**Issue by EranOfek** [blumzi/LAST_issues#71]
ocs@last04w:~$ systemctl start last-pipeline2
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'last-pipeline2.service'.
Multiple identities can be used for authentication:
 1.  ocs,,, (ocs)
 2.  enrico,,, (enrico)
Choose identity to authenticate as (1-2): 1
Password: 
==== AUTHENTICATION COMPLETE ===
ocs@last04w:~$

**Comment by EastEriq** [comment]
You can delete my account, if it troubles you

Il 3 dic 2024 15:41, Eran Ofek ***@***.***> ha scritto:
Caution: External Sender. Do not click on links or open attachments unless you recognize the sender.


***@***.***:~$ systemctl start last-pipeline2
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'last-pipeline2.service'.
Multiple identities can be used for authentication:

  1.  ocs,,, (ocs)
  2.  enrico,,, (enrico)
Choose identity to authenticate as (1-2): 1
Password:
==== AUTHENTICATION COMPLETE ===
***@***.***:~$

**Comment by blumzi** [comment]
Solved by removing user enrico
