### ISSUE TITLE
LAST 06e doesn't save images

### ISSUE THREAD

**Issue by EranOfek** [blumzi/LAST_issues#74]
WHile taking images with M6. Images are saved on 6w, but not on 6e.
Likely related to the fact this is a new computer.

**Comment by EastEriq** [comment]
How did you check, by looking into the directory `/last06e` on last06w perhaps?

I cannot reproduce. I just took images with `Unit.takeExposure`, on last06e, and
```
ocs@last06e:/last06e/data1/archive/LAST.01.06.01/new$ ls /last06?/data?/archive/LAST.01.06.0?/new
/last06e/data1/archive/LAST.01.06.01/new:
LAST.01.06.01_20241224.084153.451_clear_080+21_001_001_001_sci_raw_Image_1.fits

/last06e/data2/archive/LAST.01.06.02/new:
LAST.01.06.02_20241224.084151.032_clear_080+21_001_001_001_sci_raw_Image_1.fits
```
however, mount points on last06e may be not correct. Note that the above didn't list images in `/last06w`m though these two were reported as written:
```
{08:41:57.414|obs.unitCS[06]} Writing image /last06w/data1/archive/LAST.01.06.03/new/LAST.01.06.03_20241224.084152.958_clear_080+21_001_001_001_sci_raw_Image_1.fits to disk
{08:41:55.737|obs.unitCS[06]} Writing image /last06w/data2/archive/LAST.01.06.04/new/LAST.01.06.04_20241224.084151.408_clear_080+21_001_001_001_sci_raw_Image_1.fits to disk
```
In fact 
```
ocs@last06e:/last06e/data1/archive/LAST.01.06.01/new$ ls -ld /last0??
drwxr-xr-x 2 root root    0 Dec 14 01:54 /last04e
drwxr-xr-x 5 root root 4096 Dec  1 13:55 /last04w
drwxr-xr-x 5 root root 4096 Dec  1 15:44 /last06e
drwxr-xr-x 2 root root    0 Dec 23 19:34 /last06w
```
the mount point `/last04w` however does not see the images saved on 6w.

Conversely, on last06w the mount point `/last06e` is empty

**Comment by EastEriq** [comment]
Same context of #63 I'd say

**Comment by EranOfek** [comment]
I see it now - didn't work during the night.
Will assume the problem is now solved.
