### ISSUE TITLE
last-tool request

### ISSUE THREAD

**Issue by EranOfek** [blumzi/LAST_issues#83]
In Last-tool, if doesn't exist, please create the calib, failed, new directories - e.g., in:
/last07e/data1/archive/LAST.01.07.01/

**Comment by blumzi** [comment]
I can, of course, do that by I strongly suggest that the pipeline creates the directories by itself and not depend on external software.  It'll make it more robust.

**Comment by EranOfek** [comment]
ok - I will take responsibility.

**Comment by EranOfek** [comment]
Apparently, the mkdir line is already in the code. Likely some sort of a bug. Will open in AstroPack
