### ISSUE TITLE
names of last04e and last04w not set

### ISSUE THREAD

**Issue by noralinn** [blumzi/LAST_issues#9]
ssh ocs@last04e doesn't work and the last-asroot also skips these machines. Instead one has to type the IP address to reach these computers.

**Comment by EastEriq** [comment]
From which machine? I don't see this problem e.g. from last01w. If you are trying from a computer inside WIS (rather than one of the observatory computers), this is NOT supposed to work in the first place, unless, locally you add aliases to your /etc/hosts file, AFAIK.

**Comment by noralinn** [comment]
Thanks!

From my desktop machine in the office it works for all except M4. So maybe that due to a problem on my computer.
